#numpy

In [2]:
import numpy as np

In [3]:
from time import process_time

In [5]:
python_list=[i for i in range(10000)]

start_time=process_time()

python_list=[i+5 for i in python_list]

end_time=process_time()

print(end_time-start_time)

0.0006887810000009154


In [14]:
np_array=np.array([i for i in range (10000)])

start_time = process_time()

np_array = np_array + 5

end_time = process_time()

print(end_time - start_time)


0.00016907400000043538


In [16]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [18]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [24]:
a = np.array([(1,2,3,4),(7,8,5,4)])
print(a)
a.shape

[[1 2 3 4]
 [7 8 5 4]]


(2, 4)

In [26]:
b=np.array([(1,2,3,4),(6,7,8,9)],dtype=float)
print(b)
b.shape

[[1. 2. 3. 4.]
 [6. 7. 8. 9.]]


(2, 4)

In [28]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [32]:
z=np.full((3,4),2)
print(z)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [34]:
r=np.eye((5))
print(r)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [36]:
#create a numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.5559895  0.8798689  0.03664095 0.93361889]
 [0.98795055 0.94275991 0.86979642 0.99851777]
 [0.33369201 0.52927585 0.71382862 0.87677245]]


In [39]:
#random integer values array in specific range
c=np.random.randint(2,100,(4,5))
print(c)

[[79 36 90  4 72]
 [35 12 76 10 60]
 [18 18 65 69 64]
 [57 60  4 50 13]]


In [41]:
#array with evenly spaced values
d=np.linspace(2,30,5) #(5 is no of elements reqd)
print(d)

[ 2.  9. 16. 23. 30.]


In [44]:
d=np.arange(2,30,5) # 5 indicates diff between elements
print(d)

[ 2  7 12 17 22 27]


In [46]:
#convert list to np array
list1=[12,13,14,15]
np_array=np.asarray(list1)
print(np_array)
type(np_array)

[12 13 14 15]


numpy.ndarray

In [48]:
#analysing a numpy array
c= np.random.randint(2,100,(5,5))
print(c)


[[68 19 45  3 25]
 [17 90 13 86 12]
 [63 85 23 73 24]
 [54 26 75  4 56]
 [12 55  8 43 75]]


In [50]:
#dimension of array
c.shape

(5, 5)

In [52]:
#no of dimensions
print(c.ndim)

2


In [54]:
#no of elemnts
print(c.size)

25


In [55]:
#checking datatype
print(c.dtype)

int64


mathematical operation sin np array


In [57]:
list1=[1,2,3,5]
list2=[4,6,7,8]
print(list1+list2) #concatenates the list

[1, 2, 3, 5, 4, 6, 7, 8]


In [58]:
a= np.random.randint(0,10,(3,3))
b=np.random.randint(5,20,(3,3))


In [60]:
print(a)
print(b)

[[9 5 6]
 [7 1 2]
 [2 4 1]]
[[ 5  8 18]
 [ 5  6 16]
 [14 14 11]]


In [63]:
print(a+b)

print(a-b)

print(a*b)

print(a/b)

[[14 13 24]
 [12  7 18]
 [16 18 12]]
[[  4  -3 -12]
 [  2  -5 -14]
 [-12 -10 -10]]
[[ 45  40 108]
 [ 35   6  32]
 [ 28  56  11]]
[[1.8        0.625      0.33333333]
 [1.4        0.16666667 0.125     ]
 [0.14285714 0.28571429 0.09090909]]


In [66]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,2))
print(np.divide(a,b))

[[14 13 24]
 [12  7 18]
 [16 18 12]]
[[  4  -3 -12]
 [  2  -5 -14]
 [-12 -10 -10]]
[[18 10 12]
 [14  2  4]
 [ 4  8  2]]
[[1.8        0.625      0.33333333]
 [1.4        0.16666667 0.125     ]
 [0.14285714 0.28571429 0.09090909]]


array manipulation

In [75]:
trans=np.transpose(a)
print(trans)


[[6 7 1]
 [4 9 5]
 [9 4 6]
 [4 5 5]]


In [70]:
a= np.random.randint(0,10,(3,4))
print(a)

[[6 4 9 4]
 [7 9 4 5]
 [1 5 6 5]]


In [74]:
b=a.reshape(4,3)
print(b)

[[6 4 9]
 [4 7 9]
 [4 5 1]
 [5 6 5]]
